PATCHER_DIR=
FONTS_DIR=
OUTPUT_DIR=
BUILD_FLAGS=--complete --no-progressbars -q

PATCHER_SCRIPT=$(PATCHER_DIR)/font-patcher
GLYPH_DIR=$(PATCHER_DIR)/src/glyphs

# FIXME: Currently the file names generated by the patcher script do not match the pattern expected by this makefile.
#        This is not critical, but it is just lame and may cause problems in the future.
#        Namely this causes the rebuild of all patched fonts because the expected files are not there as far as make is concerned.

SRC_FONTS=$(wildcard $(FONTS_DIR)/*.ttf)
PATCHED_FONTS=$(patsubst $(FONTS_DIR)/%.ttf,$(OUTPUT_DIR)/%.ttf,$(SRC_FONTS))

all-fonts: $(PATCHED_FONTS)

$(OUTPUT_DIR)/%.ttf: $(FONTS_DIR)/%.ttf
	fontforge --script $(PATCHER_SCRIPT) $(BUILD_FLAGS) --outputdir $(OUTPUT_DIR) --glyphdir $(GLYPH_DIR)/ $?

.PHONY: all-fonts list-fonts
